# fly.toml file generated for sneako-protohackers on 2023-01-03T10:27:48+01:00

app = "sneako-protohackers"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
RUST_LOG = "info"

[[services]]
  internal_port = 7878
  processes = ["app"]
  protocol = "udp"

  [[services.ports]]
    handlers = []
    port = "7878"

  [[services.udp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
